package uk.gov.di.authentication.shared.entity;

public enum CountType {
    ENTER_PASSWORD("ENTER_PASSWORD"),
    ENTER_SMS_CODE("ENTER_SMS_CODE"),
    ENTER_AUTH_APP_CODE("ENTER_AUTH_APP_CODE"),
    ENTER_EMAIL_CODE("ENTER_EMAIL_CODE"),
    ENTER_EMAIL("ENTER_EMAIL");

    //    MULTIPLE_INCORRECT_MFA_CODES_KEY_PREFIX('MULTIPLE_INCORRECT_MFA_CODES_KEY_PREFIX'),
    //    MULTIPLE_INCORRECT_PASSWORDS_PREFIX('MULTIPLE_INCORRECT_PASSWORDS_PREFIX')
    //    MULTIPLE_INCORRECT_REAUTH_EMAIL_PREFIX('MULTIPLE_INCORRECT_REAUTH_EMAIL_PREFIX')
    //    MULTIPLE_INCORRECT_PASSWORDS_REAUTH_PREFIX('MULTIPLE_INCORRECT_PASSWORDS_REAUTH_PREFIX')

    private String value;

    CountType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}
